"""Shared oMLX runtime and per-request policy constants."""

SPECPREFILL_KEEP_PCT = 0.2
SPECPREFILL_THRESHOLD_TOKENS = 1024
VLM_MTP_DRAFT_BLOCK_SIZE = 3
PAGED_SSD_CACHE_MAX_SIZE = "10GB"
HOT_CACHE_MAX_SIZE = "4GB"
